# Prepare environment for building docker images
sudo: required
services:
  - docker
# setup environment for java
language: java
jdk:
  - openjdk12
# skip "mvn install -skipTexts=true" before building
install: true
env:
  - SONAR_HOST=https://sonar.ftk.de NODE_VERSION=12
git:
  depth: false
script:
  # exit script when error occurs
  - set -e
  # set specific node version
  - nvm use $NODE_VERSION
  # prepare settings.xml: add nexus credentials from environment variables
  - sed -e "s/{NEXUS_USERNAME}/$NEXUS_USERNAME/g" -e "s/{NEXUS_PASSWORD}/$NEXUS_PASSWORD/g" <.travis.settings.xml >$HOME/.m2/settings.xml
  - bash ./.travis.build.sh

# Cache local maven repository to speed up build
# Remove packages from local maven repository before caching to avoid errors when refactoring maven structure
before_cache:
  - rm -rf $HOME/.m2/repository/io/sapl
cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
