spring:
  application.name: sapl-server-lt
management:
  endpoint:
    health:
      show-details: always
io.sapl.pdp.embedded:
  pdp-config-type: FILESYSTEM
loader.path: /pdp/data/lib
logging.level:
  io.sapl: INFO   
  org.springframework: INFO