io.sapl:
  pdp.embedded:
    pretty-print-reports: false
    print-trace: false
    print-json-report: false
    print-text-report: true     
spring:
  profiles.active: local
  application.name: sapl-server-lt
management:
  endpoint:
    health:
      show-details: always
loader.path: /pdp/data/lib
