spring:
  profiles.active: h2, ssl

logging.level:
  org.atmosphere: WARN
  web: INFO

vaadin:
  blacklisted-packages: org/eclipse

# Security (BCrypt encoded client-secret (raw secret: Fa4zvYQdiwHZVXh))
io.sapl:
  server-ce:
    key: user
    secret: $2a$10$PhobF71xYb0MK8KubWLB7e0Dpl2AfMiEUi9dkKTbFR4kkWABrbiyO
