# Security (BCrypt encoded client-secret (raw secret: Fa4zvYQdiwHZVXh))
io.sapl:
  server:
    admin-username: user
    encoded-admin-password: "{bcrypt}$2a$10$PhobF71xYb0MK8KubWLB7e0Dpl2AfMiEUi9dkKTbFR4kkWABrbiyO"
# H2
spring:
  h2:
    console.enabled: false
  datasource:
    url: jdbc:h2:mem:pdp-server-ce.db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: create
    open-in-view: false
# SSL
server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:keystore.p12
    key-store-password: changeme
    key-password: changeme
    key-alias: netty
