apiVersion: v1
kind: Service
metadata:
  name: sapl-server-lt
spec:
  type: NodePort
  selector:
    app: sapl-server-lt
  ports:
    - protocol: TCP
      name: http
      # The nodePort defines the port to be accessed by a client outside of the cluster
      nodePort: 30004
      # The targetPort defines is the port on the POD that requests get sent to
      targetPort: 8080
      # The port exposes the service on the specified port internally within the cluster.
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sapl-server-lt
  labels:
    app: sapl-server-lt
spec:
  selector:
    matchLabels:
      app: am-backend-service
  replicas: 1
  template:
    metadata:
      labels:
        app: sapl-server-lt
    spec:
      containers:
        - name: sapl-server-lt
          image: nexus.openconjurer.org:30300/sapl-server-lt:2.0.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
      imagePullSecrets:
        - name: regcred