name: build_documentation

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Check out
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Configure servers
      uses: s4u/maven-settings-action@v2.3.0
      with:
        githubServer: false
        servers: |
          [{
              "id": "sapl", 
              "username": "${{ secrets.GHUB_USERNAME }}",
              "password": "${{ secrets.GHUB_ACCESS_TOKEN }}"
           },{
              "id": "ghcr.io",
              "username": "${{ secrets.GHUB_USERNAME }}", 
              "password": "${{ secrets.GHUB_ACCESS_TOKEN }}"
           },{
              "id": "github", 
              "username": "${{ secrets.GHUB_USERNAME }}",
              "password": "${{ secrets.GHUB_ACCESS_TOKEN }}"
           }]
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v2      
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build and push SAPL Server LT Docker image
      run: |
        mvn -B build -pl sapl-documentation || exit 1
    - name: Deploy Documnetation
      uses: hpcodecraft/action-deploy-workspace-to-repo@v2.2
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        SRC_FOLDER: sapl-documentation/target/generated-docs
        DEST_OWNER: ${{ secrets.GHUB_USERNAME }}
        DEST_REPO: sapl-pages
        DEST_BRANCH: master
        DEST_FOLDER: docs
        DEST_PREDEPLOY_CLEANUP: "rm -r docs/*"
