name: build_documentation

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
    - name: Check out
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Maven dependencies
      uses: actions/cache@v2      
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build Documentation
      run: mvn -B generate-resources -pl sapl-documentation

    - name: Remove Files not to push
      run: |
        rm sapl-documentation/target/generated-docs/*.pdf
        rm sapl-documentation/target/generated-docs/*.ebnf

    - name: Push Documnetation to Website
      uses: hpcodecraft/action-deploy-workspace-to-repo@v2.2
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GHUB_ACCESS_TOKEN }}
        SRC_FOLDER: sapl-documentation/target/generated-docs
        DEST_OWNER: heutelbeck
        DEST_REPO: temporary-test
        DEST_BRANCH: main
        DEST_FOLDER: docs
        DEST_PREDEPLOY_CLEANUP: "rm -rf docs/*"        
