name: Test and Deploy for Master

on:
  push:
    branches: [master]
    paths-ignore: ['sapl-documentation/**']
  
jobs:
  tests:
    strategy:
      matrix:
        java: [ '11', '16' ]
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Run Tests on ${{ matrix.os }} with JDK ${{ matrix.java }}
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        # avoid shallow clone to ensure correct sonarqube auto assignment
        fetch-depth: 0
                
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v2      
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Run tests with maven 
      run: mvn -B test

  analyze:  
    needs: [tests]
    name: Perform Static code analysis and calculate test coverage (JDK 11 and Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        # avoid shallow clone to ensure correct sonarqube auto assignment
        fetch-depth: 0
        
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 11

    - name: Configure servers
      uses: s4u/maven-settings-action@v2.3.0
      with:
        githubServer: false
        servers: |
          [{
              "id": "github", 
              "username": "${{ secrets.GHUB_USERNAME }}",
              "password": "${{ secrets.GHUB_ACCESS_TOKEN }}"
           }]
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v2      
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Run analysis (JaCoCo, Sonar) 
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.host.url=https://sonar.ftk.de -Dsonar.login=${SONAR_TOKEN} -Dsonar.exclusions=**/xtext-gen/**/*,**/xtend-gen/**/*,**/emf-gen/**/*
      