name: pull_request
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Check out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Configure servers
      uses: s4u/maven-settings-action@v2.3.0
      with:
        githubServer: false
        servers: |
          [{
              "id": "ossrh", 
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_PASSWORD }}"
            },{
              "id": "ghcr.io",
              "username": "${{ secrets.GHUB_USERNAME }}", 
              "password": "${{ secrets.GHUB_ACCESS_TOKEN }}"
            },{
              "id": "github", 
              "username": "${{ secrets.GHUB_USERNAME }}",
              "password": "${{ secrets.GHUB_ACCESS_TOKEN }}"
            }]
    
    - name: Cache Maven dependencies
      uses: actions/cache@v2      
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          
    - name: Build with Maven (JUnit, JaCoCo)
      run: mvn -U -B --fail-at-end -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn org.jacoco:jacoco-maven-plugin:prepare-agent verify org.jacoco:jacoco-maven-plugin:report

    - name: Publish Test Report
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1

    - name: Clean up local repository before caching
      run: rm -rf /.m2/repository/io/sapl
